# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deneb Solutions Limited
img: ./Deneb_sml_logo.jpg

description: > # this means to ignore newlines until "baseurl:"
  Samuel Rowe works as a Cloud engineer and Dev Ops consultant and uses this blog to share his ideas and experiences in streamlining cloud integration services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ds.limited" # the base hostname & protocol for your site
google_username: sam.rowe@deneb.co.uk
twitter_username: sam_rowe
github_username:  Sam-Rowe
linkedin_username:  samuelcprowe

# Build settings
markdown: kramdown